#!/usr/bin/perl

# Copyright (C) 2010   Keith Amling, keith.amling@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

$| = 1;

use strict;
use warnings;

use FringeUtils::Amling::ForkManager;
use FringeUtils::Amling::Table;
use Getopt::Long;

my $parallel_limit = -1;
my $sleep = 2000;

my @options =
(
    'j|parallel=i' => \$parallel_limit,
    's=i' => \$sleep,
    'help!' => sub { usage(0); },
);

GetOptions(@options) || usage(1);

my %args;
$args{'limit'} = $parallel_limit;
my $fm = FringeUtils::Amling::ForkManager->new(%args);
my @s0;
for(my $id = 0; $id < @ARGV; ++$id)
{
    my $file = $ARGV[$id];
    my @stat = stat $file;
    die unless(@stat);
    push @s0, $stat[7];
    my $cb = sub
    {
        system('nice', '-n', '20', 'bzip2', '--best', '--', $file);
    };
    $fm->add_job($id, $cb, []);
}
my @done = map { 0 } @ARGV;
my $prev_table = '';
my $first = 1;
while(1)
{
    if($first)
    {
        $first = 0;
    }
    else
    {
        my $results = $fm->wait_all($sleep);
        for(keys(%$results))
        {
            $done[$_] = 1;
        }
    }
    my @table;
    push @table,
    [
        ['L', 'File'],
        ['L', 'Before'],
        ['L', 'After'],
        ['L', 'Result'],
    ];
    push @table,
    [
        ['-'],
        ['-'],
        ['-'],
        ['-'],
    ];
    my @s1;
    for(my $id = 0; $id < @ARGV; ++$id)
    {
        my $file = $ARGV[$id];
        my $s1;
        my @stat = stat "$file.bz2";
        my $result = '';
        if(@stat)
        {
            $s1 = format_size($stat[7]);
            if($done[$id])
            {
                $result = $s0[$id] ? sprintf("%0.02f%%", 100 * $stat[7] / $s0[$id]) : 'N/A';
            }
        }
        else
        {
            $s1 = "...";
        }
        push @table,
        [
            ['L', $file],
            ['L', format_size($s0[$id])],
            ['L', $s1],
            ['R', $result],
        ];
    }
    my $table = FringeUtils::Amling::Table::format_table(\@table);
    if($table ne $prev_table)
    {
        print "\n$table";
        $prev_table = $table;
    }
    last unless(grep { !$_ } @done);
}

sub usage
{
    my $ec = shift;

    print <<EOF;
Usage: $0 <options> <files>
   {-j | --parallel} <int>   Run this many executions in parallel.
   --help                    Print this help.
EOF

    exit $ec;
}

# TODO: unify with disk-hogs?
sub format_size
{
    my $size = shift;

    my $scale = 0;
    my @scale = ("", "K", "M", "G", "T");
    while($scale + 1 < @scale && $size >= 1024)
    {
        ++$scale;
        $size /= 1024;
    }

    # stupid printf, I can't get what I want from it
    my $mantissa = sprintf("%0.2f", $size);
    $mantissa =~ s/0*$//;
    $mantissa =~ s/\.$//;

    return $mantissa . $scale[$scale];
}
